micropython/micropython-esp32-ulp

.gitignore
.travis.yml
tests/00_run_tests.sh
tests/compat/alu.S
tests/esp32.ulp.ld

- download and build micropython and binutils-esp32
- run existing test cases using micropython
- build files under tests/compat/*.S using both tools and compare
- one simple test case (tests/compat/alu.S) included
See https://github.com/ThomasWaldmann/py-esp32-ulp/issues/13

ci: run tests in Travis Ci

---

.gitignore
.travis.yml
tests/00_unit_tests.sh
tests/01_compat_tests.sh

- place binutils and micropython builds into folds
- split test scripts into unit tests and compatibility tests
- make compatibility test output less noisy when tests pass
- use `xxd -e` instead of hexdump to display binaries in groups of 4 bytes, little-endian format.
Example of a passing test:
```
$ ./01_compat_tests.sh
Testing compat/alu.S
Building using py-esp32-ulp
Building using binutils
Build outputs match
```
Example of a failing test:
```
$ ./01_compat_tests.sh
Testing compat/alu.S
Building using py-esp32-ulp
Building using binutils
Build outputs differ!
Compatibility test failed for compat/alu.S
py-esp32-ulp log:
Symbols:
text section:
70400039
724ffff3
724a5a55
70600039
726ffff3
726a5a55
7207fff5
7208000c
720ffff3
72000016
7227fff5
7228000c
722ffff3
72200016
50000005
size: 60 …
```

ci: clean up output, use xxd when dumping binaries

---

esp32_ulp/__main__.py
esp32_ulp/assemble.py
esp32_ulp/nocomment.py
tests/assemble.py
tests/nocomment.py

Now supported:
```
/* C-style */
// C-style
```

comment removal by state machine, fixes #17

---

esp32_ulp/__main__.py
esp32_ulp/assemble.py
esp32_ulp/util.py
tests/assemble.py

this enables the assembler to translate larger source files without running out of memory.

call the garbage collector now and then

---

.github/workflows/run_tests.yaml

Now the list includes all dependencies we need, even if the build image
we're building on already has some of these installed. Hopefully this
has a documentation benefit and makes future updates to later OS images
easier.

update build dependencies, including all we need

---

.github/workflows/run_tests.yaml
esp32_ulp/assemble.py
esp32_ulp/opcodes.py
tests/compat/jumps.S

This PR is meant to fix #41 .
The PR is more of a prototype for now (not finished). I raised it to be able to:
1. discuss the implementation of "emit multiple instructions"
2. get ideas on a behaviour of binutils-esp32ulp that I cannot yet explain.
---
**1. opcode -> Multiple instructions**
For now the implementation (see commit fa09eb3) works by the `i_jumpr` and `i_jumpr` methods returning a `tuple` when multiple instructions should be emitted, and the assembler testing for "is this a tuple" and if so, it looping over the elements. Otherwise it does what it did before, i.e. adds 1 instruction to the section. The current structure for this logic feels a bit rough, but for now I intend mostly to get feedback on the approach.
To help this, for pass 1, when we're not yet calling the `i_*` …

Fix relative jumps

---

esp32_ulp/assemble.py
tests/assemble.py
tests/compat/fixes.S

I'm now trying to send more smaller PRs - this is the first one that moves us towards being able to assemble all the currently skipped examples from the binutils-esp32ulp test suite (to resolve #49).
The esp32ulp_all.s code has a `nop;` statement in it, and this commit adds support for the `;` which functions as a statement separator. (See the commit message of ce005e3 for more detail).
Side-note: Currently, due to the way labels are handled/detected, there must be a space between a `;` and the next statement, if there is another statement on the same line. The way labels are handled is another thing to be fixed (see [esp32ulp_all.s:2](https://github.com/espressif/binutils-esp32ulp/blob/249ec34cc2c9574a86f3f86bbb175a863f988bcf/gas/testsuite/gas/esp32ulp/esp32/esp32ulp_all.s#L2), where a …

support the ';' line separator character, aka statement separator

---

esp32_ulp/assemble.py
esp32_ulp/opcodes.py
tests/02_compat_rtc_tests.sh
tests/assemble.py
tests/compat/fixes.S
tests/compat/jumps.S

Some more fixes to move us towards being able to assemble all the currently skipped examples from the binutils-esp32ulp test suite (to resolve #49).
This PR contains a few fixes - felt it was easier to send them as one PR, than 1 PR per commit.
The commits are independent of each other and can be reviewed one by one. They contain commit messages explaining what they each fix. Each commit also has a reference to the issue it fixed in the relevant binutils-esp32ulp test.
The last commits enables the tests that can now pass because of the fixes. 2 more files to go.

More fixes towards v1.0

---

README.rst
docs/index.rst
docs/preprocess.rst
examples/README
setup.py

This PR aims to improve the README, as suggested in #49, to make it easier to read and understand how to get started with py-esp32-ulp.
The main change to the README might be easier to look at by looking at the [file](https://github.com/ThomasWaldmann/py-esp32-ulp/blob/eba2ddb/README.rst) rather than the [patch](https://github.com/ThomasWaldmann/py-esp32-ulp/commit/eba2ddb).
* I have added "installation" and "getting started" sections and rearranged content to try get the user going as quickly as possible. Information such as what is supported and what minimum MicroPython version is required is further down.
* In general, I have also tried to shorten existing text to make it more concise where possible.
* There is now also a build-status badge just below the heading.
The README has gotten …

Improve README

---

.github/workflows/publish.yml
setup.py

This PR adds a GitHub Actions workflow for publishing our upip package to PyPi. It resolves #58.
I was inspired to create this by this article: https://simonwillison.net/2021/Nov/4/publish-open-source-python-library/, even though I now saw, that GitHub offers a workflow template for this too, using an action from its Actions Marketplace.
Instead of using a hardcoded version number during the build, setup.py now uses setuptools-scm to derive a useful/relevant version from git metadata (tags/commits).
The below is documentation mainly for once the PR has been merged, and for how to then test it and later release 1.0.0.
The workflow in this PR will require setting up 2 repository secrets (Settings -> Secrets -> Actions secrets -> New repository secret), namely `TEST_PYPI_API_TOKEN` and …

Publish to pypi

---

MANIFEST.in

This PR changes MANIFEST.in to exclude everything other than the main source of py-esp32-ulp, such as documentation and tests.
The approach used here is to exclude all files from the root (since the main source lives in esp32_ulp/) and also exclude all other directories by name. (i.e. include all, and then remove most things)
Semantically, I would have wanted to express the opposite: "exclude all, and only include esp32_ulp/". However, this also ended up excluding metadata files that setuptools put in the archive. I could include them again explicitly, but I think this could cause unexpected (hard-to-debug) behaviour in the future, if for example a future version of setuptools added more metadata files, or changed the name of this metadata file. It feels like something that could easily …

Only package the main source for PyPI

---

esp32_ulp/util.py
tests/compat/expr.S
tests/util.py

Support uppercase hex character in expressions. 0xFF is now treated identically to 0xff. As is 0Xff or 0xFf.
Resolves #71

Allow uppercase hex chars in expressions

---

examples/readgpio.py

This PR adds a simple example for reading a GPIO pin with the ULP coprocessor.
When running this, the ULP will read the current GPIO value (0 for off, 1 for on) into a memory location, and a loop at the end of the example will continuously print the value in that memory location. This allows seeing the value update as one toggles the input to the GPIO pin between HIGH to LOW (e.g. by connecting and disconnecting a wire from VCC (3V3) to GPIO4).

add example: reading a GPIO input with the ULP coprocessor

---

examples/blink.py

The blink example was toggling the GPIOs "output enable" state, instead of keeping "output enable" on and then toggling the output value of the pin. (reported in #78)
This PR fixes the problem by enabling "output enable" at the start, and then only toggling the output value of the pin "on" and "off". (Documentation for the used register constants can be found [here](https://github.com/espressif/esp-idf/blob/v4.4.1/components/soc/esp32/include/soc/rtc_io_reg.h#L43) and [here](https://github.com/espressif/esp-idf/blob/v4.4.1/components/soc/esp32/include/soc/rtc_io_reg.h#L19))
The change was tested with a logic analyser to confirm the expected change.
More details in the commit message.
Resolves issue #78.

Fix blink example by correctly toggling output

---

.github/workflows/run_tests.yaml

The MicroPython project changed their CI scripts slightly, which resulted in the unix port binary being output to a subdirectory (`build-standard`) instead of the current directory as before. This broke our build process.
This commit updates our build script to search for the `micropython` binary in the correct subdirectory.
Fixes #81

Use micropython from new build location during build

---

.github/workflows/run_tests.yaml

GitHub has deprecated the ubuntu-18.04 builder image. So before that builder image is entirely removed, this PR updates the build process to use the ubuntu-20.04 image instead.
This commit also installs an older version of GCC (v7) because [binutils-esp32ulp](https://github.com/espressif/binutils-esp32ulp) does not build successfully on Ubuntu 20.04 with its default GCC version (v9). (Solution was found here: https://github.com/espressif/binutils-esp32ulp/issues/19#issuecomment-945091131)
Fixes: #80
PS: Ubuntu 22.04 no longer has GCC v7 in its repository, which is why this PR only changes to Ubuntu 20.04 for now (should last a while). It appears binutils-esp32ulp has some bigger change in the making ([see this comment](https://github.com/espressif/binutils-esp32ulp/issues/23#issuecomment-1 …

Update builder image to ubuntu-20.04

---

.github/workflows/publish.yml
.github/workflows/run_tests.yaml

This commit fixes 2 Github Deprecations:
1. Node12 Actions GitHub deprecated Node12 for running actions. In this commit we're switching to the latest version of action/checkout, which has been updated to run on a newer Node version. See: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
2. set-output/set-state commands GitHub deprecated the ::set-output command which we use to pass PATH information between build steps. This commit switches to echoing a key=value pair to the environment file $GITHUB_OUTPUT. See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See the recent [Github Actions run](https://github.com/micropython/micropython-esp32-ulp/actions/runs/5263843356) …

Fix GitHub Deprecation warnings

---

.github/workflows/run_tests.yaml
README.rst
docs/index.rst
tests/01_compat_tests.sh
tests/02_compat_rtc_tests.sh

This is a precursor step to adding support for the ULP-FSM of the ESP32-S2/S3.
This change changes where we get the esp32ulp assembler/linker from:
* we now use the latest maintained version (binutils-gdb instead of binutils-esp32ulp)
* we download pre-built binaries, rather than building ourselves - to save time.
Espressif moved where they maintain the ULP assembler (see https://github.com/espressif/esp-idf/commit/a9bd454), and this changes switches to the new esp32ulp assembler/linker, which is also what the latest ESP-IDF uses.
Since Espressif publishes a list of pre-built tools, which includes the esp32ulp assembler/linker, we now download the pre-built binaries, rather than building them ourselves.
The new esp32ulp assembler/linker only has a single set of binaries across all esp32 …

Use new binutils gdb

---

README.rst
docs/index.rst
package.json
tools/genpkgjson.py

This PR adds a `package.json` file to allow installing `micropython-esp32-ulp` with the `mip` package manager on modern MicroPythons.
To install with mip, one would run:
```py
import mip
mip.install('github:micropython/micropython-esp32-ulp')
mip.install('https://raw.githubusercontent.com/wnienhaus/micropython-esp32-ulp/mip_support/package.json')
```
This PR also adds a tool for generating the contents of `package.json`, so it doesn't have to be handcrafted whenever files are added/removed.
To generate/update `package.json`, run from repo root as follows:
```py
python3 tools/genpkgjson.py > package.json
```
(instead of `python3`, `micropython` can also be used)
Note: at present MIP does not support any way to specify repo-relative urls, so at present the generated json will point to …

Add package.json for MIP package manager

---

tests/01_compat_tests.sh
tests/02_compat_rtc_tests.sh

Peripheral register definitions were moved to a new directory inside the ESP-IDF: components/soc/{cpu_type}/register.
This change caused our compat tests to fail because they depended on predefined register constants.
This PR resolves the issue by adding the new directory to GCC's include search path using the -I option.
Additionally, all header files in this new directory are now added to the DefinesDB for the compat tests with RTC macros.
Fixes #101.

Fix compat tests due to esp-idf moving include files

---

docs/index.rst

Avoid rising "unicode exception" when running from mp1.24, see issue #99

Open ulp file in binary mode instead of text mode

---

.github/workflows/run_tests.yaml

GitHub has deprecated and removed the ubuntu-20.04 builder image.
This PR updates the build process to use the ubuntu-22.04 image instead.
Tested locally with [act](https://nektosact.com/) that all tests still pass.
GitHub's announcement: https://github.com/actions/runner-images/issues/11101

Update builder image to ubuntu-22.04

---

examples/fade_s2.py
examples/tsens_s2.py

An example that uses ULP self-modifying code to create a PWM-like LED dimming effect on GPIO 15.

Add LED Fade Example
